# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 15:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=40)),
                ('added_by', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('username', models.CharField(max_length=38)),
                ('pw_hash', models.CharField(max_length=225)),
                ('dh', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wl_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_wl', to='wishexam.Items')),
                ('wl_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_wl', to='wishexam.Users')),
            ],
        ),
        migrations.AddField(
            model_name='items',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_quote', to='wishexam.Users'),
        ),
    ]
